#!/bin/bash 

MAIL_FILE=/tmp/log/mail
JAR_PATH=/root/bin/slp

if [ $# != 1 ]; then
    echo Error usage!
    exit 1
fi

if [ ! $TIME_INT ]; then
    TIME_INT=20
fi
echo $$ > $1
while true
do
    touch $MAIL_FILE
    java -jar $JAR_PATH/logger.jar >> $MAIL_FILE
    sleep $TIME_INT
done

