#!/bin/bash 

MAIL_FILE=mail
JAR_PATH=/home/jackson/codes
if [ ! $TIME_INT ]; then
    TIME_INT=20
fi
echo $$ > piffile
while true
do
    touch $MAIL_FILE
    java -jar $JAR_PATH/logger.jar >> $MAIL_FILE
    echo $TIME_INT
    sleep $TIME_INT
done

